github.com:
    users:
        StudiosServer:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: StudiosServer
